import { FamilyMember, Relationship, Conversation, Post } from "./types";

export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
    {
        id: "1",
        userId: "user-1",
        firstName: "Olav",
        lastName: "Nordmann",
        birthDate: "1950-05-15",
        gender: "male",
        bio: "Bestefar og familiens overhode. Elsker fiske og historier fra gamle dager.",
        role: "admin",
    },
    {
        id: "2",
        userId: "user-2",
        firstName: "Kari",
        lastName: "Nordmann",
        birthDate: "1952-08-20",
        gender: "female",
        bio: "Bestemor og familiens hjerte. Lager verdens beste vafler.",
        role: "admin",
    },
    {
        id: "3",
        userId: "user-3",
        firstName: "Per",
        lastName: "Nordmann",
        birthDate: "1980-03-10",
        gender: "male",
        bio: "Pappa. Jobber som ingeniør og liker å snekre på hytta.",
        role: "contributor",
    },
    {
        id: "4",
        userId: "user-4",
        firstName: "Lise",
        lastName: "Nordmann",
        birthDate: "1982-07-25",
        gender: "female",
        bio: "Mamma. Lærer og glad i turer i skog og mark.",
        role: "contributor",
    },
    {
        id: "5",
        userId: "user-5",
        firstName: "Anna",
        lastName: "Nordmann",
        birthDate: "2010-01-05",
        gender: "female",
        bio: "Datter. Går på skole og spiller håndball.",
        role: "contributor",
    },
    {
        id: "6",
        userId: "user-6",
        firstName: "Lars",
        lastName: "Nordmann",
        birthDate: "2012-11-15",
        gender: "male",
        bio: "Sønn. Liker Lego og fotball.",
        role: "contributor",
    },
];

export const MOCK_RELATIONSHIPS: Relationship[] = [
    { id: "r1", fromId: "1", toId: "2", type: "spouse" },
    { id: "r2", fromId: "1", toId: "3", type: "parent" },
    { id: "r3", fromId: "2", toId: "3", type: "parent" },
    { id: "r4", fromId: "3", toId: "4", type: "spouse" },
    { id: "r5", fromId: "3", toId: "5", type: "parent" },
    { id: "r6", fromId: "3", toId: "6", type: "parent" },
    { id: "r7", fromId: "4", toId: "5", type: "parent" },
    { id: "r8", fromId: "4", toId: "6", type: "parent" },
    { id: "r9", fromId: "5", toId: "6", type: "sibling" },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        id: "c-1",
        familyId: "f-1",
        isGroup: true,
        name: "Hyttetur 2024",
        participantIds: ["1", "3", "4"],
        messages: [
            {
                id: "m-1",
                conversationId: "c-1",
                senderId: "1",
                content: "Hei! Hvordan går det med planleggingen av hytteturen?",
                timestamp: "2024-01-01T10:00:00Z",
                read: true,
            },
            {
                id: "m-2",
                conversationId: "c-1",
                senderId: "3",
                content: "Det går bra! Vi tenkte å reise opp på fredag.",
                timestamp: "2024-01-01T10:05:00Z",
                read: true,
            },
            {
                id: "m-3",
                conversationId: "c-1",
                senderId: "1",
                content: "Høres bra ut. Vi kommer etter på lørdag morgen.",
                timestamp: "2024-01-01T10:10:00Z",
                read: true,
            },
        ],
        updatedAt: "2024-01-01T10:10:00Z",
    },
    {
        id: "c-2",
        familyId: "f-1",
        isGroup: false,
        participantIds: ["2", "4"],
        messages: [
            {
                id: "m-4",
                conversationId: "c-2",
                senderId: "2",
                content: "Har du oppskriften på eplekaken?",
                timestamp: "2024-01-02T14:00:00Z",
                read: true,
            },
            {
                id: "m-5",
                conversationId: "c-2",
                senderId: "4",
                content: "Ja, jeg sender den til deg nå!",
                timestamp: "2024-01-02T14:05:00Z",
                read: true,
            },
        ],
        updatedAt: "2024-01-02T14:05:00Z",
    },
];

export const MOCK_POSTS: Post[] = [
    {
        id: "p-1",
        familyId: "f-1",
        authorId: "3",
        content: "Fantastisk dag på fjellet! 🏔️",
        timestamp: "2024-01-05T12:00:00Z",
        likes: ["1", "2", "4"],
        comments: [
            {
                id: "co-1",
                postId: "p-1",
                authorId: "1",
                content: "Ser herlig ut!",
                timestamp: "2024-01-05T12:30:00Z",
            },
        ],
    },
    {
        id: "p-2",
        familyId: "f-1",
        authorId: "5",
        content: "Se hva jeg lagde på skolen i dag! 🎨",
        timestamp: "2024-01-06T15:00:00Z",
        likes: ["3", "4", "1", "2"],
        comments: [],
    },
];
